"""initial schema

Revision ID: 61ed14fedec9
Revises: 
Create Date: 2026-08-31 09:58:18.410231
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "61ed14fedec9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "wifi_networks",
        sa.Column("wifi_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("network_name", sa.String(length=255), nullable=True),
        sa.Column("mac_address", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("wifi_id"),
    )
    op.create_index(
        op.f("ix_wifi_networks_mac_address"), "wifi_networks", ["mac_address"], unique=True
    )
    op.create_index(op.f("ix_wifi_networks_user_id"), "wifi_networks", ["user_id"], unique=False)
    op.create_table(
        "alert_logs",
        sa.Column("alert_id", sa.UUID(), nullable=False),
        sa.Column("sender_user_id", sa.UUID(), nullable=False),
        sa.Column("wifi_id", sa.UUID(), nullable=False),
        sa.Column("target_devices", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sender_user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["wifi_id"],
            ["wifi_networks.wifi_id"],
        ),
        sa.PrimaryKeyConstraint("alert_id"),
    )
    op.create_index(op.f("ix_alert_logs_created_at"), "alert_logs", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_alert_logs_sender_user_id"), "alert_logs", ["sender_user_id"], unique=False
    )
    op.create_table(
        "devices",
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("wifi_id", sa.UUID(), nullable=False),
        sa.Column("device_name", sa.String(length=255), nullable=True),
        sa.Column("device_type", sa.String(length=50), nullable=False),
        sa.Column("device_os_version", sa.String(length=50), nullable=True),
        sa.Column("push_token", sa.String(length=500), nullable=True),
        sa.Column("battery_level", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wifi_id"], ["wifi_networks.wifi_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("device_id"),
    )
    op.create_index(op.f("ix_devices_user_id"), "devices", ["user_id"], unique=False)
    op.create_index(op.f("ix_devices_wifi_id"), "devices", ["wifi_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_devices_wifi_id"), table_name="devices")
    op.drop_index(op.f("ix_devices_user_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_alert_logs_sender_user_id"), table_name="alert_logs")
    op.drop_index(op.f("ix_alert_logs_created_at"), table_name="alert_logs")
    op.drop_table("alert_logs")
    op.drop_index(op.f("ix_wifi_networks_user_id"), table_name="wifi_networks")
    op.drop_index(op.f("ix_wifi_networks_mac_address"), table_name="wifi_networks")
    op.drop_table("wifi_networks")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
