"""notification preferences and password reset

Revision ID: aff527dded91
Revises: 61ed14fedec9
Create Date: 2026-08-31 10:33:27.111726
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "aff527dded91"
down_revision: str | None = "61ed14fedec9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("notifications_enabled", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column(
        "users", sa.Column("sound_enabled", sa.Boolean(), server_default="true", nullable=False)
    )
    op.add_column(
        "users", sa.Column("vibration_enabled", sa.Boolean(), server_default="true", nullable=False)
    )
    op.add_column(
        "users", sa.Column("password_reset_token_hash", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "users", sa.Column("password_reset_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_reset_expires_at")
    op.drop_column("users", "password_reset_token_hash")
    op.drop_column("users", "vibration_enabled")
    op.drop_column("users", "sound_enabled")
    op.drop_column("users", "notifications_enabled")
    # ### end Alembic commands ###
